### ISSUE TITLE
Unable to download ILAMB-Data

### ISSUE THREAD

**Issue by sterlingbaldwin** [rubisco-sfa/ILAMB#19]
The command `ilamb-fetch --remote_root http://ilamb.ornl.gov/ILAMB-Data --no-check-certificate` fails because of a timeout issue. It looks like the data's been moved.

**Comment by nocollier** [comment]
The default location for the ILAMB data has been off `ilamb.ornl.gov` for a while now. We had too many problems with keeping that location up consistently. If you just remove the `--remote_root` argument, it will default to the correct location, or specify this:

`--remote_root https://www.ilamb.org/ILAMB-Data/`

Thanks! Let me know if that doesn't solve it :)

**Comment by sterlingbaldwin** [comment]
Thanks, looks like the docs have been updated too.
