### ISSUE TITLE
Use GitHub URLS instead of old BitBucket urls in documentation?

### ISSUE THREAD

**Issue by ian-bertolacci** [rubisco-sfa/ILAMB#21]
All the links to code I've followed in the documentation still point to the old BitBucket repo, as opposed to this GitHub repo.

**Comment by ian-bertolacci** [comment]
And not just links, but urls, such as the git URL for cloning the ILAMB repo.

**Comment by nocollier** [comment]
Well, you tried to warn me. Thought I fixed this and it burnt some students... Sigh. Fixed in #27.
