### ISSUE TITLE
Can custom confrontations be used from configuration script?

### ISSUE THREAD

**Issue by ian-bertolacci** [rubisco-sfa/ILAMB#22]
The tutorial page on custom confrontations does not indicates if it can be used in a configuration script (such as sample.cfg from the example: https://www.ilamb.org/Downloads/minimal_ILAMB_data.tgz)

Diving into the code, it seems that Scoreboard is set up for constructing custom confrontation objects, but there doesn't appear to be a way to specify the confrontation type (ctype) of a configuration script node.
By default, a node is given the ctype value None, which is then inherited from it's parent nodes (via InheritVariableNames), but there is nothing that reads (specifically, ParseScoreboardConfigureFile does not read anything) from the configuration script and assigns it to a ctype member.

Is it currently possible to use a custom confrontation from a configuration script?

**Comment by nocollier** [comment]
By default, ILAMB tries to use one of the confrontations installed with the package. However, if none of these types match, then I will try to import the ctype specified in the configure file. See here:

https://github.com/rubisco-sfa/ILAMB/blob/master/src/ILAMB/Scoreboard.py#L331

So, if I have a configure file:
```
[h1: Junk]
[h2: Stuff]
[Yay]
ctype = MyStuff
source = "stuff.nc"
```
where I want to use a confrontation I wrote. Mystuff.py is:
```
class MyStuff():
    def __init__(self,**keywords):
        print("Yup, here we made this kind")
```
which is just some junk for now. Then when I execute ILAMB:

```
ilamb-run --config test.cfg --model_root ~/data/ILAMB/MODELS/CLM/
```
I will import this class from Mystuff.py if I can find it in the path. So you will also need to set:
```
export PYTHONPATH=$PYTHONPATH:$PWD
```
in order for me to find it.

**Comment by ian-bertolacci** [comment]
Ah I was missing the part where node.ctype gets assigned, but that happens here: https://github.com/rubisco-sfa/ILAMB/blob/master/src/ILAMB/Scoreboard.py#L172
