### ISSUE TITLE
NaN problem

### ISSUE THREAD

**Issue by minxu74** [rubisco-sfa/ILAMB#25]
I think that ILAMB already handles the float pointing exception very well. But today I ran ILAMBv2.5 with the hash tag 672ce4048 and found that there are still some NaNs for the actual scores in the result tables. When ILAMB tries to scale these scores to compute the relative scores, the NaN is included and it made all other valid actual scores to be NaNs and the metrics for all models showed missing values in the land page.

**Comment by nocollier** [comment]
Despite my best efforts, we still get Nan's creeping in there. I think that the commit 65b4b67 will completely stamp out the problem.
