### ISSUE TITLE
ilamb-doctor is not compatible with python 3

### ISSUE THREAD

**Issue by melodyjulia** [rubisco-sfa/ILAMB#28]
It uses dict.has_key() method which is abandoned in python3.

**Comment by nocollier** [comment]
Thanks for the report, but I am not seeing its use? Perhaps you are running from the last release version and not the tip of master?

**Comment by melodyjulia** [comment]
Yes, I'm using the release version of 2.5 from conda-forge without checking the tip of the master.

**Comment by nocollier** [comment]
It is a tool that we do not use often and when I converted to python3 I missed it. It is corrected in master, we need to make another release soon. If you feel you need it, just clone this repository and install with pip from conda.

**Comment by melodyjulia** [comment]
Thank you very much.
