### ISSUE TITLE
RMSE and Seasonal Cycle compsite scores are NOT generated for Ecosystem and Carbon Cycle

### ISSUE THREAD

**Issue by minxu74** [rubisco-sfa/ILAMB#29]
The composite **RMSE and Seasonal Cycle** scores are not generated and written to the "scalars.json" by ILAMB. As the figure shown below, there are no 
"RMSE and Seasonal Cycle score global" objects under the top metric of  "Ecosystem and Carbon Cycle" compared with "Hydrology Cycle"

![image](https://user-images.githubusercontent.com/8196287/94970192-1d879480-04d2-11eb-848c-ec0f192b11ef.png)

**Comment by nocollier** [comment]
Fixed in 2.6.
