### ISSUE TITLE
Variable.__init__: shifting of 'lon' and 'lon_bnds' incorrect

### ISSUE THREAD

**Issue by goujou** [rubisco-sfa/ILAMB#3]
Calling the constructor Variable() with

lon = [  5.     112.5    299.9783] and lon_bnds = None, leads by line 156 to
lon = [  5.       112.5      -60.021698]. Assuming spatial data, line 176 produces

lon_bnds =
[[ -48.75       58.75    ]
 [  58.75       26.239151]
 [  26.239151 -146.282547]], 

where 112.5 and and 299.9783 already do not match their bounds.
This leads later to an assertion error in line 193, when

lon = [-60.021698   5.       112.5     ] and
lon_bnds =
[[-180.       -146.282547]
 [ -48.75       58.75    ]
 [  58.75      180.      ]].

**Comment by nocollier** [comment]
I have a fix for this coming, it solves the problem you presented but it causes some failures elsewhere. Will update this once I have it ironed out.
```
lon = [  5.     112.5    299.9783]
Variable: temp
--------------
                unit: 1
          isTemporal: True (10)
           isSpatial: True (4,3)
           isLayered: False
          nDatasites: N/A
           dataShape: (10, 4, 3)
             dataMax: 9.944607e-01
             dataMin: 4.029044e-03
            dataMean: 4.748512e-01

v.lon = [-60.0217   5.     112.5   ]
v.lon_bnds = [[-92.53255 -27.51085]
              [-27.51085  58.75   ]
              [ 58.75    166.25   ]]
```

**Comment by nocollier** [comment]
Should be fixed here in this commit, pushed into master: https://github.com/rubisco-sfa/ILAMB/commit/15da3a53d13794f173ed2b3213b37785d9682a41
