### ISSUE TITLE
sym/bias plot range bug?

### ISSUE THREAD

**Issue by mcguirepatr** [rubisco-sfa/ILAMB#45]
What's the purpose of this line of code?
https://github.com/rubisco-sfa/ILAMB/blob/a040a962a4007ec293b9b759b54c2f54114edd64/src/ILAMB/Confrontation.py#L481

As written, it is taking the maximum of two always-identical values.
Patrick McGuire

**Comment by mcguirepatr** [comment]
It looks like that line of code hasn't changed, even in the master.
Is there any chance of looking at this?
Patrick McGuire

**Comment by nocollier** [comment]
Wow 2021 Nathan, clearly this is wrong. Have a branch open with this fix in it and whatever else we need when fixing your issues.
