### ISSUE TITLE
Should the environment yml file list udunits2 instead of udunits?

### ISSUE THREAD

**Issue by jsta** [rubisco-sfa/ILAMB#46]
I'm getting an error on conda environment creation:

> PackagesNotFoundError: The following packages are not available from current channels:

>  - udunits

**Comment by nocollier** [comment]
I think the yml file should not list udunits at all, it is cf_units job to
get that dependency right. At one point I recall adding it because it fixed
an error I was getting. It should be removed.

Also note that the last release of ILAMB is available in conda as well in
the conda-forge channel.
