### ISSUE TITLE
Why adding the print or logger.debug or logger.info in the py files under the src/ILAMB doesn't work ?

### ISSUE THREAD

**Issue by XueliHuo** [rubisco-sfa/ILAMB#55]
Hi,

I have a question to ask about the way to debug. I installed ilamb and ran the example provided in the tutorial successfully. Then I applied to use it with my own data. However, there is an error saying VarNotComparable. And I tried to add the print or logger.debug or logger.info in the ilamblib.py to print out the values of some variables. However, I can't see the message print out in either the log file or the ILAMB03.log file. So my question why the print or logger added in the source py files under src/ILAMB doesn't work? What should I do if I want to print out the values of some variables ?

Thanks.

**Comment by minxu74** [comment]
Hi @XueliHuo, I think that you can directly use python "print" to print out the debug info that you want. They will be dumped to the last ILAMBxx.log.

**Comment by XueliHuo** [comment]
print or logger.debugger. or logger.info doesn't work in my case. I was running ILAMB on Cheyenne, and I tried multiple times to print out after I added the print or the other two logger's into the py file, neither worked because the expected info didn't appear in ILABM0*.log or the other log file under logs directory. My guess is that after I modify the py files in src/ILAMB, should I reinstall ilamb by using the conda ?

**Comment by nocollier** [comment]
I am not totally clear on what you are doing, but if you modify the source
code of ILAMB locally on your system, you will need to reinstall ILAMB.
However, doing so with conda will reinstall the latest version again and
not contain your changes. To install your local changes as the version of
ILAMB you will use, you should navigate to the ILAMB directory and issue
`pip install ./`.

Other than this, I am not sure why the logger isn't working on Cheyenne,
but we have had this problem before. Print statements should always work.
