### ISSUE TITLE
Running ILAMB with model output split across multiple years

### ISSUE THREAD

**Issue by SeanBryan51** [rubisco-sfa/ILAMB#81]
Should it be possible to run ILAMB with model output that is split across multiple years? I would like to avoid creating a "combined copy" of my model outputs if possible and point ILAMB to each "per year" model output, i.e.
```
ILAMB_ROOT/MODELS/
└── CABLE
    ├── cable_out_000.nc  # year: 1900
    ├── cable_out_001.nc  # year: 1901
    ├── ...
    └── cable_out_XXX.nc  # year: N
```

If I try to run ILAMB with the above directory structure (with two model output files corresponding to two consecutive years), ILAMB will throw an error in the final post processing step:
```
[INFO][0][<module>] Linux gadi-cpu-clx-1223.gadi.nci.org.au 4.18.0-477.15.1.el8.nci.x86_64 #1 SMP Sun Jul 16 11:36:47 AEST 2023 x86_64 x86_64
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/matplotlib (3.7.2)
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/netCDF4 (1.6.0)
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/cf_units (3.2.0)
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2023-10-31 15:39:01.421098
[INFO][0][MakeComparable][Albedo/GEWEX.SRB][CABLE] Spatial data was clipped from the reference:  before: [ 36 360 720] after: [ 36 279 720]
[INFO][0][AnalysisMeanStateSpace][albedo] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][albedo] RMSE scored using Collier2018
[INFO][0][confront][Albedo/GEWEX.SRB][CABLE] Success
[DEBUG][0][WorkPost][Albedo/GEWEX.SRB][CABLE]
Traceback (most recent call last):
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/bin/ilamb-run", line 616, in WorkPost
    c.modelPlots(m)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 925, in modelPlots
    var = Variable(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 941, in FromNetCDF4
    t, t_bnd, cbounds, begin, end, calendar = GetTime(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.04/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 359, in GetTime
    raise ValueError(msg)
ValueError: Time intervals defined in ./_build/RadiationandEnergyCycle/Albedo/GEWEX.SRB/GEWEX.SRB_CABLE.nc:time_bnds_ are not continuous

[INFO][0][<module>][total time] 40.5 s
```

The above exception occurs due to problematic time bounds in `_build/RadiationandEnergyCycle/Albedo/GEWEX.SRB/GEWEX.SRB_CABLE.nc`. Inspecting the time bounds with `ncdump` shows that boundary points are not contiguous:
```
   time_bnds_ =
  49261, 49290.5,
  49290.5, 49320,
  49320, 49349.5,
  49349.5, 49380,
  49380, 49410.5,
  49410.5, 49441,
  49441, 49471.5,
  49471.5, 49502.5,
  49502.5, 49533,
  49533, 49563.5,
  49563.5, 49594,
  49594, 49624.5,   <--- these two time bounds do not share a boundary
  49625.5, 49655.5, <---
  49655.5, 49685.5,
  49685.5, 49714.5,
  49714.5, 49745,
  49745, 49775.5,
  49775.5, 49806,
  49806, 49836.5,
  49836.5, 49867.5,
  49867.5, 49898,
  49898, 49928.5,
  49928.5, 49959 ;
```

It looks like these time bounds are being set in [`CombineVariables`](https://github.com/rubisco-sfa/ILAMB/blob/8d1e9cfb4a2193bd3415d7746c2c80410d780bb0/src/ILAMB/ilamblib.py#L2576) - when creating the merged variable from the list of variables, the time bounds for each variable are concatenated together, however, a shared boundary point between each variable is not created. See below:
https://github.com/rubisco-sfa/ILAMB/blob/8d1e9cfb4a2193bd3415d7746c2c80410d780bb0/src/ILAMB/ilamblib.py#L2641-L2651

For reference, this is the configuration and command I use to run ILAMB:
```
# test.cfg
[h1: Radiation and Energy Cycle]
bgcolor = "#FFECE6"

[h2: Albedo]
variable = "albedo"
alternate_vars = "Albedo"

[GEWEX.SRB]
source = "DATA/albedo/GEWEX.SRB/albedo_0.5x0.5.nc"
```
```
ilamb-run --config test.cfg --model_root $ILAMB_ROOT/MODELS/ --regions global --model_year 1903 1985 --study_limits 1985 1987
```

**Comment by nocollier** [comment]
Yes, your CABLE output should run. ILAMB does not require a specific
structure in your output files. It rather loops through all files and
builds a small database (dictionary) of which variables are found in which
files. Concatenation occurs automatically in the routine you found.

A problem that I faced early on in coding ILAMB (before tools like xarray)
was handling the different calendars. Modeling centers use many different
ones and also have different conventions about which time is reported in
the interval (beginning, middle, end). This made aligning with
observational products very hard and so I started requiring that the time
variable have a 'bounds' array which is part of the CMIP standard anyway.
If your model doesn't have it, I guess at where you have placed the time in
the interval and build one for you.

So it could be that my generated time bounds for CABLE are wrong or that
CABLE's included bounds are not continuous. Can you make a few files
available and I will work on it?

**Comment by SeanBryan51** [comment]
Thank you for the reply. My model outputs do not contain a time bounds attribute so the time bounds must be generated by ILAMB. It looks like it would be tricky for ILAMB to generate the correct time bounds when model outputs are split across multiple years, especially at the start and end of the time bounds array.

I think the best solution here is to add a post processing step which adds the correct time bounds explicitly to all my model output files prior to running ILAMB. An alternative could be to get ILAMB to somehow do this but I suspect this might be a bit involved and would depend on whether this functionality would be useful for the community.

**Comment by SeanBryan51** [comment]
Specifying the time bounds explicitly in the model outputs has fixed the error. Closing this issue.
