### ISSUE TITLE
Save png of the dashboard? 

### ISSUE THREAD

**Issue by JessicaNeedham** [rubisco-sfa/ILAMB#91]
I'd like to include ILAMB results in talks and posters but haven't figured out a good way to save the figure showing the initial orange and purple model columns and observation rows other than a screenshot. Is there a better way to do this? I have found the pngs that are saved for each model v observation comparison, but I don't see a png for the dashboard. Am I missing it? Or would it be possible to add this functionality?

**Comment by nocollier** [comment]
I have not found a great way of doing this other than a screenshot. One issue among many is that I am not a web developer :/ and am not sure how.

What I recommend is loading the page up and changing the zoom level such that the columns of your main page fill the horizontal space on your screen and then use a full screen capture program like:

https://chromewebstore.google.com/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en

which will take several shots and then piece them together. You at least get a better resolution this way.

**Comment by JessicaNeedham** [comment]
Thanks Nate! I realised I could change the html to make the background white - that way when I take screen shots it looks better on a white background. But your way of getting high res versions is better.  

![Screenshot 2024-06-20 at 10 27 49](https://github.com/rubisco-sfa/ILAMB/assets/10586303/1ae6bc90-5f67-4def-8f3b-27d8194660cd)

**Comment by nocollier** [comment]
Good tip though, thanks for that.
